### ISSUE TITLE
Non-Binary Sentiment

### ISSUE THREAD

**Issue by jakesyl** [ravikiranj/twitter-sentiment-analyzer#9]
Is there anyway to get the sentiment as a number?  So say .64 would be less positive then .76.

**Comment by ravikiranj** [comment]
* For Native Bayes, take a look at [NaiveBayesClassifier.prob_classify](http://www.nltk.org/_modules/nltk/classify/naivebayes.html#NaiveBayesClassifier.prob_classify)
* For NLTK's MaxEnt classifier, take a look at [nltk.classify.maxent.MaxentClassifier.prob_classify](http://www.nltk.org/api/nltk.classify.html#nltk.classify.maxent.MaxentClassifier.prob_classify).
* For libsvm, take a look at [svm_predict function](https://github.com/cjlin1/libsvm/blob/master/python/svmutil.py)

**Comment by jakesyl** [comment]
Alright thanks a lot, any idea where I could get a bag-of-words for analysis?
